### ISSUE TITLE
多次加载图片,内存已然飙升!

### ISSUE THREAD

**Issue by Quanhua-Guan** [OpenFibers/OTLargeImageReader#1]
多次加载图片,内存依然飙升!
第一次效果都意外的好!

**Comment by foobra** [comment]
@Quanhua-Guan 啥意思, 就是用这个库之后, 第二三次也要飙升起来?

**Comment by OpenFibers** [comment]
@Quanhua-Guan 调用频率多高？可以把用法贴出来吗？thx
‘我这里是好的’
/Users/openthread/Desktop/Screen Shot 2015-06-08 at 10.57.29 AM.png

**Comment by OpenFibers** [comment]
@Quanhua-Guan 调用频率多高？可以把用法贴出来吗？thx
‘我这里是好的’
/Users/openthread/Desktop/Screen Shot 2015-06-08 at 10.57.29 AM.png

**Comment by OpenFibers** [comment]
@Quanhua-Guan 调用频率多高？可以把用法贴出来吗？thx
‘我这里是好的’

**Comment by OpenFibers** [comment]
@Quanhua-Guan 调用频率多高？可以把用法贴出来吗？thx
‘我这里是好的’

**Comment by Quanhua-Guan** [comment]
- 就是使用@OpenFibers原来的代码,真机运行,我是用的5s. 
- 重现操作步骤: 每隔大概4秒点击一次"Compress image using OTLargeImageReader"按钮.

**Comment by OpenFibers** [comment]
@Quanhua-Guan 多久之后会出现问题？会飙升多少内存？感谢

**Comment by Quanhua-Guan** [comment]
一般是100M左右 @O pen Fi b er s

**Comment by Quanhua-Guan** [comment]
![1](https://cloud.githubusercontent.com/assets/1726550/8048471/493b0282-0e84-11e5-8693-d3a0f8993a32.png)
@OpenFibers

**Comment by Quanhua-Guan** [comment]
![Uploading 1.png…]()

**Comment by Quanhua-Guan** [comment]
![Uploading 12.png…]()

**Comment by Quanhua-Guan** [comment]
以下是运行截图@OpenFibers.(抱歉刚才误操作)
![12](https://cloud.githubusercontent.com/assets/1726550/8048817/cfa7b3a2-0e88-11e5-8799-d5da6b933c61.png)

**Comment by OpenFibers** [comment]
@Quanhua-Guan 看截图并没有什么异常，内存已经回到4了

**Comment by Quanhua-Guan** [comment]
@OpenFibers 我想得到的结果是让每次图片加载消耗的内存都可以控制在一个很低的水平, 比如iPhone上10M以内.  事实上, 测试的时候时,有时可以控制在5M左右(用Demo提供的图片).

**Comment by Quanhua-Guan** [comment]
~_~
